import {localDay,schedulesFor,recordFor,lockPeriod,addCorrection} from './archive-model.mjs?v=20260920-lock1';
export function mountArchive(host,bridge){
  host.innerHTML=`<div class="eog-eyebrow">Your medication library</div><h3>Saved history</h3><p>Find past days, protect the original record, and prepare a doctor review. Locking preserves what you recorded; it does not confirm that unrecorded doses were taken.</p><p data-archive-storage role="status"></p><div class="eog-actions"><button type="button" data-archive-sync>Open my account</button></div><div class="med-range"><label>Browse month<input type="month" data-history-month></label><label>Find a medicine<input type="search" data-history-search placeholder="Medicine name"></label><label>Show<select data-history-filter><option value="all">All days with a plan or notes</option><option value="locked">Locked days</option><option value="open">Not yet locked</option></select></label></div><div data-history-days class="archive-day-list"></div><details><summary>Save & lock a period</summary><p>Choose up to 366 completed days. Doctor reports cover up to 93 days at a time. Days with no plan or notes are left out. Already locked days stay unchanged. Correct a locked record later with a dated note; the original stays visible.</p><div class="med-range"><label>From<input type="date" data-lock-from required></label><label>To<input type="date" data-lock-to required></label></div><div class="eog-actions"><button type="button" data-lock-preview>Review before locking</button><button type="button" data-archive-report>Doctor report for this period (includes notes)</button><button type="button" data-archive-backup>Download full backup</button></div></details><p data-archive-message role="status"></p><dialog class="eog-surface" data-archive-dialog><form><h3 data-archive-title></h3><p data-archive-explanation></p><label data-correction-label hidden>What needs correcting?<textarea data-correction maxlength="1000" rows="4" placeholder="Describe the correct medicine, dose, time or observation, and why it differs."></textarea></label><p data-archive-error role="alert"></p><div class="eog-actions"><button type="submit" data-archive-confirm>Save & lock</button><button type="button" data-archive-cancel>Cancel</button></div></form></dialog>`;
  const $=s=>host.querySelector(s),dialog=$('[data-archive-dialog]');let scope='',action=null;
  function resetRange(){const month=$('[data-history-month]').value;if(!/^\d{4}-\d{2}$/.test(month))return;const start=month+'-01',end=localDay(new Date(Number(month.slice(0,4)),Number(month.slice(5)),0)),yesterday=localDay(new Date(Date.now()-86400000));$('[data-lock-from]').value=start;$('[data-lock-to]').value=end<yesterday?end:yesterday;}
  function message(text){$('[data-archive-message]').textContent=text;}
  function review(from,to){try{const {data:next,count}=lockPeriod(bridge.data(),from,to);const dates=Object.keys(next.lockedDays).filter(d=>d>=from&&d<=to&&!bridge.data().lockedDays?.[d]);let unknown=0;for(const date of dates)for(const s of schedulesFor(next,date))if(!s.asNeeded)for(const time of s.times)if(!recordFor(next,s.id,date,time)||recordFor(next,s.id,date,time).status==='unknown')unknown++;action={type:'lock',from,to,scope:bridge.scope()};$('[data-archive-title]').textContent='Save & lock '+count+' day(s)';$('[data-archive-explanation]').textContent=from+' to '+to+'. '+unknown+' scheduled dose(s) remain Not recorded. The original medicines, times, intake records and notes will become read-only. Later corrections are added as dated notes.';$('[data-correction-label]').hidden=true;$('[data-archive-confirm]').textContent='Save & lock these days';$('[data-archive-error]').textContent='';dialog.showModal();}catch(e){message(e.message);}}
  $('[data-archive-sync]').onclick=()=>{const account=document.querySelector('#private-account');if(!account){message('Private accounts are unavailable in this preview. Use the live app to sign in.');return;}if(bridge.account())account.querySelector('[data-sync]')?.click();else account.scrollIntoView({block:'start'});};
  $('[data-lock-preview]').onclick=()=>review($('[data-lock-from]').value,$('[data-lock-to]').value);
  $('[data-archive-cancel]').onclick=()=>dialog.close();
  dialog.querySelector('form').onsubmit=e=>{e.preventDefault();if(!action||action.scope!==bridge.scope()){dialog.close();return;}try{const next=action.type==='lock'?lockPeriod(bridge.data(),action.from,action.to).data:addCorrection(bridge.data(),action.date,$('[data-correction]').value);bridge.archiveSave(next);dialog.close();message(action.type==='lock'?'Days saved and locked. Check the storage status above before closing.':'Correction note saved alongside the original locked record.');refresh();}catch(e){$('[data-archive-error]').textContent=e.message;}};
  $('[data-archive-report]').onclick=()=>bridge.generateSummary({from:$('[data-lock-from]').value,to:$('[data-lock-to]').value,includeNotes:true});
  $('[data-archive-backup]').onclick=()=>document.querySelector('#med-backup')?.click();
  for(const key of ['month','search','filter'])$('[data-history-'+key+']').addEventListener(key==='search'?'input':'change',()=>{if(key==='month')resetRange();refresh();});
  function refresh(){
    if(scope!==bridge.scope()){scope=bridge.scope();dialog.close();action=null;$('[data-correction]').value='';$('[data-history-month]').value=bridge.day().slice(0,7);$('[data-history-search]').value='';$('[data-history-filter]').value='all';resetRange();message('');}
    const data=bridge.data(),month=$('[data-history-month]').value,query=$('[data-history-search]').value.trim().toLowerCase(),filter=$('[data-history-filter]').value,list=$('[data-history-days]');list.replaceChildren();
    $('[data-archive-sync]').textContent=bridge.account()?'Sync now':'Open my account';const storage=bridge.account()?document.querySelector('#private-account [data-status]')?.textContent||'Private account: check online sync status.':(document.querySelector('#tracker-storage-status')?.textContent||'Device-only storage. Sign in and use your private account to sync across devices.');$('[data-archive-storage]').textContent=storage+' Download a backup periodically; it includes locked history and correction notes.';
    if(!/^\d{4}-\d{2}$/.test(month))return;
    const count=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate();
    for(let n=count;n>=1;n--){const date=month+'-'+String(n).padStart(2,'0');if(date>localDay())continue;const schedules=schedulesFor(data,date),lock=data.lockedDays?.[date],notes=lock?lock.remarks:(data.remarks||[]).filter(r=>r.date===date);if(!schedules.length&&!notes.length||query&&!schedules.some(s=>s.name.toLowerCase().includes(query))||filter==='locked'&&!lock||filter==='open'&&lock)continue;
      let taken=0,unknown=0;for(const s of schedules)for(const time of s.times){const r=recordFor(data,s.id,date,time);if(r?.status==='taken')taken++;else if(!s.asNeeded&&(!r||r.status==='unknown'))unknown++;}
      const row=document.createElement('article');row.className='archive-day';const title=document.createElement('h4');title.textContent=date+' · '+(lock?'Locked':'Not yet locked');const info=document.createElement('p');info.textContent=taken+' dose(s) recorded taken · '+unknown+' not recorded'+(lock?' · saved '+new Date(lock.lockedAt).toLocaleString():'');const names=document.createElement('p');names.className='eog-small';names.textContent=[...new Set(schedules.map(s=>s.name))].join(' · ');const actions=document.createElement('div');actions.className='eog-actions';row.append(title,info,names,actions);
      const button=(label,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=fn;actions.append(b);};button('Open day',()=>bridge.selectDay(date));button('Doctor report',()=>bridge.generateSummary({from:date,to:date,includeNotes:true}));
      if(lock){button('Add correction note',()=>{action={type:'correct',date,scope:bridge.scope()};$('[data-archive-title]').textContent='Correction note · '+date;$('[data-archive-explanation]').textContent='The original stays locked. This dated note will appear beside it and in doctor reports that include notes.';$('[data-correction-label]').hidden=false;$('[data-correction]').value='';$('[data-archive-confirm]').textContent='Save correction note';$('[data-archive-error]').textContent='';dialog.showModal();});for(const c of lock.corrections){const p=document.createElement('p');p.className='archive-correction';p.textContent='Correction · '+new Date(c.recordedAt).toLocaleString()+': '+c.text;row.append(p);}}else if(date<localDay())button('Save & lock',()=>review(date,date));list.append(row);
    }
    if(!list.children.length)list.textContent='No matching history in this month. Choose another month or clear the medicine search.';
  }
  // Mirror the real account status; a lock is not proof that cloud sync succeeded.
  const observer=new MutationObserver(()=>{const status=document.querySelector('#private-account [data-status]');if(bridge.account()&&status){const text=status.textContent+' Backups include locked history and correction notes.';if($('[data-archive-storage]').textContent!==text)$('[data-archive-storage]').textContent=text;}});
  observer.observe(document.querySelector('#medication'),{subtree:true,childList:true,characterData:true});
  // The equality check above avoids repeated updates from our own status writes.

  refresh();return {refresh};
}
