import {recordInventory} from './import-records.mjs?v=20260924-simple1';
export function mountPatientFocus(section,bridge){
  const style=document.createElement('link');style.rel='stylesheet';style.href=new URL('./focus.css?v=20260924-simple1',import.meta.url).href;document.head.append(style);let view='daily';
  function open(next,{scroll=true}={}){view=next;refresh();if(scroll)section.querySelector('#med-focus')?.scrollIntoView({block:'start'});}
  function refresh(){
    let toolbar=section.querySelector('#med-focus');if(!toolbar){toolbar=document.createElement('div');toolbar.id='med-focus';toolbar.innerHTML='<nav aria-label="Medication workspace"><button type="button" data-workspace="daily">Daily record</button><button type="button" data-workspace="history">Saved history</button><button type="button" data-workspace="summary">Summary</button><button type="button" data-workspace="more">More</button></nav><div class="focus-save"><p data-focus-status role="status"></p><div class="eog-actions"><button type="button" data-focus-save>Save / Sync</button><button type="button" data-focus-account>My account</button></div></div>';section.querySelector('h2').after(toolbar);toolbar.querySelectorAll('[data-workspace]').forEach(b=>b.onclick=()=>open(b.dataset.workspace));toolbar.querySelector('[data-focus-save]').onclick=()=>{section.querySelector('#med-save-device')?.click();if(bridge.account())section.querySelector('#private-account [data-sync]')?.click();};toolbar.querySelector('[data-focus-account]').onclick=()=>{open('more');section.querySelector('#private-account')?.scrollIntoView({block:'start'});};}
    section.dataset.workspace=view;toolbar.querySelectorAll('[data-workspace]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.workspace===view)));
    const daily=new Set(['patient-day-summary','tracker-stats','tracker-daily','tracker-remarks']);
    for(const child of section.children){if(['med-focus','patient-tools'].includes(child.id)||['DIALOG','H2'].includes(child.tagName)||child.classList.contains('eog-eyebrow')||child.id==='med-message')continue;child.dataset.focus=daily.has(child.id)?'daily':'more';}
    const p=section.querySelector('#patient-tools');if(p)for(const child of p.children)child.dataset.focus=['patient-archive','patient-import'].includes(child.id)?'history':child.id==='patient-review'?'summary':'more';
    section.querySelectorAll('.tracker-tabs,.patient-tools-nav').forEach(n=>n.dataset.focus='internal');
    const list=section.querySelector('#tracker-list');if(list)list.hidden=view!=='more';
    const title=section.querySelector(':scope>h2');if(title)title.textContent={daily:'Daily medication record',history:'Find your past records',summary:'Medication summary',more:'Plans, notes & settings'}[view];
    for(const selector of ['#med-import','#med-save-device']){const legacy=section.querySelector(selector)?.closest('.eog-panel');if(legacy)legacy.dataset.focus='internal';}
    let help=section.querySelector('#focus-more-help');if(!help){help=document.createElement('section');help.id='focus-more-help';help.className='eog-panel';help.dataset.focus='more';help.innerHTML='<h3>Keep a separate backup</h3><p>Download a backup to keep a recovery file outside this browser. To bring an old backup back, use Saved history → Bring in previous records.</p><div class="eog-actions"><button type="button" data-focus-backup>Download backup</button><button type="button" data-focus-copy>View / copy backup</button><button type="button" data-focus-import>Bring in previous records</button></div>';section.append(help);help.querySelector('[data-focus-backup]').onclick=()=>section.querySelector('#med-backup')?.click();help.querySelector('[data-focus-copy]').onclick=()=>section.querySelector('#med-view-backup')?.click();help.querySelector('[data-focus-import]').onclick=()=>{open('history');section.querySelector('[data-record-import]').open=true;};}
    let empty=section.querySelector('#focus-empty');if(!empty){empty=document.createElement('aside');empty.id='focus-empty';empty.innerHTML='<p></p><div class="eog-actions"><button type="button" data-empty-history>Find past records</button><button type="button" data-empty-plan>Add my medication plan</button></div>';section.querySelector('#med-doses')?.after(empty);empty.querySelector('[data-empty-history]').onclick=()=>open('history');empty.querySelector('[data-empty-plan]').onclick=()=>{open('more');const form=section.querySelector('#med-add');form.parentElement.open=true;form.scrollIntoView({block:'start'});};}
    empty.hidden=!!section.querySelector('#med-doses .med-dose');if(!empty.hidden){const info=recordInventory(bridge.data());empty.querySelector('p').textContent=info.schedules||info.records||info.locked?'No plan is shown for this selected day. Your past records are still stored ('+info.from+' to '+info.to+'). Open Saved history to find them.':'Start by entering your prescribed medication plan, or bring in an Eye of Garden backup under Saved history. Records save after you confirm an entry.';}
    updateStatus();
  }
  function updateStatus(){const target=section.querySelector('[data-focus-status]');if(!target)return;const cloud=section.querySelector('#private-account [data-status]'),device=section.querySelector('#tracker-storage-status');const text=bridge.account()?cloud?.textContent||'Loading private account…':device?.textContent||'Loading saved records…';if(target.textContent!==text)target.textContent=text;const save=section.querySelector('[data-focus-save]'),label=bridge.account()?'Save / Sync':'Save on this device';if(save&&save.textContent!==label)save.textContent=label;}
  const observer=new MutationObserver(updateStatus);observer.observe(section,{subtree:true,childList:true,characterData:true});
  document.addEventListener('click',e=>{const link=e.target.closest('a[href^="#patient-"], [data-shortcut], #med-doctor-summary');if(!link)return;const dest=link.getAttribute('href')||link.dataset.shortcut||'review';if(dest.includes('archive'))open('history',{scroll:false});else if(dest.includes('review'))open('summary',{scroll:false});else if(dest.includes('voice'))open('more',{scroll:false});else if(dest==='medication')open('daily',{scroll:false});},true);
  document.addEventListener('eog:workspace',e=>{if(['daily','history','summary','more'].includes(e.detail))open(e.detail,{scroll:false});});
  const brand=document.querySelector('.eog-brand');if(brand)brand.dataset.eogRoute='medication';const nav=document.querySelector('.eog-header nav');
  if(nav&&!nav.querySelector('.garden-more')){const more=document.createElement('details');more.className='garden-more';const title=document.createElement('summary');title.textContent='Garden & more';more.append(title);const menu=document.createElement('div');menu.className='garden-more-menu';more.append(menu);for(const b of [...nav.querySelectorAll('[data-eog-route]')])if(b.dataset.eogRoute!=='medication')menu.append(b);nav.append(more);menu.addEventListener('click',()=>more.open=false);}
  for(const [id,text] of [['myLeaf','Garden membership is optional and separate from your medication account. Use My account in the medication tracker to save and sync health records.'],['room','For notes saved with your medication record, use the tracker → More → Daily notes & voice. This journal is a temporary draft.']]){const page=document.getElementById(id);if(page){const note=document.createElement('p');note.className='eog-surface eog-small';note.textContent=text;page.prepend(note);}}
  refresh();return {refresh,open};
}
