import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import * as archive from './archive-model.mjs';
import {prepareRecordFile,recordInventory} from './import-records.mjs';
import {buildReport} from './records.mjs';
const source=fs.readFileSync(new URL('../medication.js',import.meta.url),'utf8');
const decl=['day','validDay','validTime','slotStart','slotEnd','validSlot','palette'].map(n=>source.match(new RegExp('  const '+n+'=[^\\n]+'))[0]).join('\n');
const context=vm.createContext({archive});
vm.runInContext(decl+'\n'+source.slice(source.indexOf('  function validate(d)'),source.indexOf('  let unreadableStoredRecord')),context);
const validate=data=>{context.input=data;return vm.runInContext('validate(input)',context);};
const current={version:1,profile:{name:'Test patient'},schedules:[{id:'a',name:'Example medicine',dose:'One tablet',start:'2026-09-01',end:'2026-09-19',times:['06:00'],intakeDay:true}],records:{}};
const original=JSON.stringify(current);
assert.throws(()=>prepareRecordFile(current,{format:'report'},validate),/not an Eye of Garden/);
assert.throws(()=>prepareRecordFile(current,{version:1,schedules:[{}],records:{}},validate),/incomplete or invalid/);
const backup={version:1,schedules:[],records:{}};
assert.equal(prepareRecordFile(current,backup,validate).kind,'backup');
assert.equal(JSON.stringify(current),original);
const locked=archive.lockPeriod(current,'2026-09-18','2026-09-19',new Date('2026-09-21T12:00:00')).data;
const restored=prepareRecordFile(locked,backup,validate).next;
assert.equal(buildReport(restored,'2026-09-18','2026-09-19').rows.length,2);
const conflict=structuredClone(locked);conflict.lockedDays['2026-09-18'].lockedAt='2026-09-22T12:00:00Z';
assert.throws(()=>prepareRecordFile(locked,conflict,validate));
const history={version:1,format:'eye-of-garden-history',id:'test-import',days:[{date:'2026-09-20',intakeDay:true,medicines:[{name:'Example medicine',dose:'Two tablets',time:'06:00',status:'unknown'}],notes:[]}]};
const imported=prepareRecordFile(current,history,validate);
assert.equal(imported.kind,'history');assert.equal(imported.days,1);
assert.equal(buildReport(imported.next,'2026-09-20','2026-09-20').rows[0].status,'unknown');
assert.equal(JSON.stringify(current),original);
assert.throws(()=>prepareRecordFile(imported.next,history,validate));
assert.equal(recordInventory(locked).locked,2);
console.log('PASS: file recognition, rejected corrupt files, no preview mutation, preserved locked history, conflicting-lock rejection, historical plans without invented intake.');
