import {prepareHistory} from './history.mjs?v=20260924-simple1';
import {preserveLockedHistory} from './archive-model.mjs?v=20260920-lock1';
const localDay=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
export function recordInventory(data,today=localDay()){
  const dates=[...Object.keys(data.dayPlans||{}),...Object.keys(data.lockedDays||{}),...Object.keys(data.records||{}).map(k=>k.split('|')[1]),...(data.remarks||[]).map(r=>r.date)];
  for(const s of data.schedules||[]){dates.push(s.start);dates.push(s.end||today);}
  dates.sort();return {from:dates[0]||'',to:dates.at(-1)||'',schedules:data.schedules?.length||0,records:Object.keys(data.records||{}).length,locked:Object.keys(data.lockedDays||{}).length,name:data.profile?.name||'No report name in file'};
}
export function prepareRecordFile(current,file,validate){
  if(file?.format==='eye-of-garden-history'){const result=prepareHistory(current,file);validate(result.next);return {next:result.next,kind:'history',days:result.preview.length,inventory:recordInventory(result.next),preview:result.preview,dates:file.days.map(d=>d.date).sort()};}
  if(file?.version!==1||!Array.isArray(file.schedules)||!file.records)throw Error('This is not an Eye of Garden record backup. Choose the .json file created with Download backup. PDF, CSV, pictures and written notes cannot be restored as medication records here.');
  try{validate(file);}catch{throw Error('Some records in this backup are incomplete or invalid. Nothing has changed. Keep the file and use a valid Eye of Garden backup.');}
  const next=preserveLockedHistory(current,file);validate(next);return {next,kind:'backup',inventory:recordInventory(file),current:recordInventory(current),dates:[]};
}
export function mountRecordImport(host,bridge){
  host.innerHTML='<details data-record-import><summary>Bring in previous records</summary><p><strong>Have an Eye of Garden backup?</strong> Choose the .json file below. We will show what is inside before saving anything. A downloaded PDF or CSV is a report, not a restorable backup.</p><label>1. Choose your record file<input type="file" data-record-file accept="application/json,.json"></label><div data-import-preview></div><label class="med-check" data-import-ack-label hidden><input type="checkbox" data-import-ack> I checked the patient name, dates and replacement details above.</label><div class="eog-actions"><button type="button" data-import-commit hidden disabled>Save reviewed records</button><button type="button" data-import-cancel hidden>Cancel</button></div><p data-import-message role="status"></p><details><summary>No backup file?</summary><p>Use More → Add a schedule to enter your prescribed medicines and dates. Use Edit this day for a specific historical day. A plan does not mean the medicines were taken: enter actual intake separately when you know it.</p><button type="button" data-manual-records>Enter medicines myself</button></details><details><summary>Recover the record from before my last import</summary><p>A recovery copy is kept on this device for the same account before an import. This restores that copy; locked days remain protected. Download your current backup first if you want to keep later changes.</p><button type="button" data-import-recovery disabled>Review recovery copy</button></details></details>';
  const $=s=>host.querySelector(s);let pending=null,source='',scope='',ticket=0;
  const recoveryKey=()=> 'eog_import_recovery_'+bridge.scope();
  const say=t=>$('[data-import-message]').textContent=t;
  function clear(){pending=null;source='';ticket++;$('[data-import-preview]').replaceChildren();$('[data-import-ack]').checked=false;for(const key of ['ack-label','commit','cancel'])$('[data-import-'+key+']').hidden=true;$('[data-import-commit]').disabled=true;}
  function show(parsed,label){const current=bridge.data(),result=prepareRecordFile(current,parsed,bridge.validate);clear();source=JSON.stringify(current);pending={parsed,scope:bridge.scope(),label};const preview=$('[data-import-preview]');const line=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;preview.append(n);};line('h4','2. Review '+label);line('p',result.kind==='backup'?'File type: Eye of Garden backup. Restoring replaces the unlocked tracker records and profile with this file. Existing locked history is kept.':'File type: historical day plans. Only the listed days change. Days with recorded intake or locks cannot be replaced. No doses will be marked taken.');const info=result.inventory;line('p','Patient: '+info.name+' · Dates: '+(info.from?info.from+' to '+info.to:'No dated entries'));line('p',info.schedules+' medicine schedules · '+info.records+' intake entries · '+info.locked+' locked days');if(result.current)line('p','Currently in this tracker: '+result.current.name+' · '+result.current.schedules+' schedules · '+result.current.records+' intake entries.');if(result.preview)for(const d of result.preview.slice(0,10))line('p',d.date+' · '+d.medicines.length+' medicine entries');line('p','Before saving, a recovery copy of your current record will be stored on this device.');for(const k of ['ack-label','commit','cancel'])$('[data-import-'+k+']').hidden=false;$('[data-import-commit]').textContent=result.kind==='backup'?'Restore reviewed backup':'Add reviewed day plans';say('Preview only. Your records have not changed.');}
  $('[data-record-file]').onchange=async e=>{clear();say('');const chosen=e.target.files?.[0],token=ticket,owner=bridge.scope();if(!chosen)return;try{if(!/\.json$/i.test(chosen.name))throw Error('Choose an Eye of Garden .json backup. A PDF, spreadsheet, photo or HTML page cannot be restored here.');if(chosen.size>2000000)throw Error('Choose a backup smaller than 2 MB.');let parsed;try{parsed=JSON.parse(await chosen.text());}catch{throw Error('This file is not readable JSON. Choose the original Eye of Garden backup file.');}if(token!==ticket||owner!==bridge.scope())return;show(parsed,chosen.name);}catch(e){if(token===ticket)say(e.message);}};
  $('[data-import-ack]').onchange=e=>$('[data-import-commit]').disabled=!e.target.checked;
  $('[data-import-cancel]').onclick=()=>{clear();$('[data-record-file]').value='';say('Import cancelled. Your records are unchanged.');};
  $('[data-import-commit]').onclick=()=>{try{if(!pending||!$('[data-import-ack]').checked)return;if(pending.scope!==bridge.scope()||source!==JSON.stringify(bridge.data()))throw Error('Your account or records changed during review. Choose the file again before saving.');const result=prepareRecordFile(bridge.data(),pending.parsed,bridge.validate);bridge.checkSize(result.next);try{localStorage.setItem(recoveryKey(),source);}catch{throw Error('There is not enough device storage to keep a recovery copy. No records were replaced. Download your current backup and free some browser storage first.');}const date=result.dates.at(-1)||result.inventory.to;bridge.importSave(result.next,date);clear();$('[data-record-file]').value='';say('Records saved to this tracker. Check the saving status above for online sync. Choose the imported month in Saved history below.');refresh();}catch(e){say(e.message);}};
  $('[data-import-recovery]').onclick=()=>{try{const raw=localStorage.getItem(recoveryKey());if(!raw)throw Error('No recovery copy is available on this device for this account.');show(JSON.parse(raw),'the recovery copy from before your last import');}catch(e){say(e.message);}};
  $('[data-manual-records]').onclick=()=>bridge.openMore();
  function refresh(){if(scope!==bridge.scope()){scope=bridge.scope();clear();$('[data-record-file]').value='';say('');}try{$('[data-import-recovery]').disabled=!localStorage.getItem(recoveryKey());}catch{$('[data-import-recovery]').disabled=true;}}
  refresh();return {refresh};
}
