import assert from 'node:assert/strict';
import {planPeriods,comparePlans,describePlan} from './plan-changes.mjs';
const row={medicine:'Example medicine',dose:'One tablet',time:'06:00',intakeDay:true,asNeeded:false,status:'unknown'};
const report={from:'2026-09-01',to:'2026-09-06',rows:[{...row,date:'2026-09-01'},{...row,date:'2026-09-02',status:'taken'},{...row,date:'2026-09-03',dose:'Half tablet'},{...row,date:'2026-09-04'},{...row,date:'2026-09-06'}]};
const periods=planPeriods(report);
assert.equal(periods.length,5);assert.equal(periods[0].to,'2026-09-02');
assert.equal(periods[1].changes[0].before[0].dose,'One tablet');assert.equal(periods[1].changes[0].after[0].dose,'Half tablet');
assert.equal(periods[2].changes[0].before[0].dose,'Half tablet');
assert.equal(periods[3].rows.length,0);assert.equal(periods[4].baseline,true);assert.equal(periods[4].changes.length,0);
assert.equal(comparePlans([row],[{...row,status:'skipped'}]).length,0);
assert.equal(comparePlans([row],[{...row,time:'06:15'}]).length,1);
assert.equal(comparePlans([row],[{...row,asNeeded:true}]).length,1);
assert.equal(comparePlans([row],[row,{...row,time:'12:00'}]).length,1);
assert.equal(comparePlans([row],[])[0].type,'No longer in recorded plan');
assert.equal(comparePlans([],[row])[0].type,'Added to recorded plan');
assert.match(describePlan([{...row,time:'01:00'}]),/next morning/);
assert.doesNotMatch(describePlan([{...row,time:'01:00',intakeDay:false}]),/next morning/);
assert.equal(planPeriods({from:'2026-09-01',to:'2026-09-03',rows:[]}).length,1);
console.log('PASS: consecutive plan periods, return to earlier plan, explicit gaps, dose/timing/frequency/PRN changes, no inference from taken/skipped status, overnight labels.');
