import {saveClip,listClips} from './audio-store.mjs';
import {validDate} from './records.mjs';
export function mountVoice(host,bridge){
  host.innerHTML=`<h3>Daily notes & voice</h3><p>Keep your observations or a doctor’s advice with the day it belongs to.</p><form data-note><label>Day<input type="date" name="date" required></label><label>Note type<select name="kind"><option value="noteType">My note</option><option value="doctorAdvice">Doctor’s advice — recorded by me</option><option value="concern">Concern to discuss</option><option value="effect">Possible side effect</option><option value="improvement">Improvement</option></select></label><label>Your note<textarea name="text" rows="4" maxlength="1000" placeholder="What would you like your doctor to know?"></textarea></label><div class="eog-actions"><button type="button" data-dictate>Speak to write</button><button type="button" data-stop-dictate hidden>Stop dictation</button><button data-save-note>Save daily note</button></div><p data-draft-status role="status"></p></form><p class="eog-small">Dictation may send audio to your browser’s speech service. Review the words before saving, especially medicine names and doses. If unavailable, use the microphone on your phone’s keyboard.</p><label>Speech language<select data-language><option value="en-SG">English</option><option value="ms-MY">Bahasa Melayu</option><option value="zh-CN">中文</option></select></label><hr><label class="med-check"><input type="checkbox" data-consent>I have permission from everyone being recorded.</label><div class="eog-actions"><button type="button" data-record>Record voice note</button><button type="button" data-stop-record hidden>Stop & save recording</button></div><p data-voice-status role="status">Recordings stay on this device. Download important recordings. Audio is not included in account backups or doctor links.</p><label>Add an existing audio recording<input data-audio-file type="file" accept="audio/*"></label><p class="eog-small">Up to 5 minutes per recording, or an audio file up to 20 MB. Keep this page open while recording. Cloud audio storage is not connected.</p><div data-clips></div>`;
  const $=s=>host.querySelector(s),form=$('[data-note]'),say=t=>$('[data-voice-status]').textContent=t,draftSay=t=>$('[data-draft-status]').textContent=t;
  let scope='',currentDay='',recorder=null,stream=null,recognizer=null,busy=false,recordTimer,clockTimer,startTime=0,urls=[],epoch=0;
  const draftKey=()=> 'eog_note_draft_'+scope;
  function saveDraft(){try{localStorage.setItem(draftKey(),JSON.stringify({date:form.elements.date.value,kind:form.elements.kind.value,text:form.elements.text.value}));draftSay('Draft saved on this device. Choose Save daily note to add it to your record.');}catch{draftSay('Draft could not be saved. Copy your words before refreshing.');}}
  form.oninput=saveDraft;
  function controls(){const recording=!!recorder&&recorder.state!=='inactive';$('[data-record]').disabled=busy||recording||!!recognizer;$('[data-stop-record]').hidden=!recording;$('[data-dictate]').disabled=busy||recording||!!recognizer;$('[data-stop-dictate]').hidden=!recognizer;$('[data-save-note]').disabled=recording||!!recognizer;form.elements.text.readOnly=!!recognizer;}
  async function clips(){const ticket=++epoch,targetScope=scope,targetDate=form.elements.date.value;try{const items=await listClips(targetScope,targetDate);if(ticket!==epoch||scope!==targetScope)return;urls.forEach(URL.revokeObjectURL);urls=[];const list=$('[data-clips]');list.replaceChildren();if(!items.length){list.textContent='No voice recordings for this day.';return;}for(const item of items){const article=document.createElement('article'),title=document.createElement('p'),audio=document.createElement('audio'),link=document.createElement('a');title.textContent=item.label+' · '+new Date(item.createdAt).toLocaleString();const url=URL.createObjectURL(item.blob);urls.push(url);audio.controls=true;audio.preload='metadata';audio.src=url;link.href=url;link.download=item.filename;link.textContent='Download recording';article.className='patient-clip';article.append(title,audio,link);list.append(article);}}catch{say('Voice storage is unavailable in this browser. Download each recording before leaving.');}}
  form.elements.date.addEventListener('change',()=>{saveDraft();clips();});
  function offerDownload(clip){const list=$('[data-clips]'),link=document.createElement('a'),url=URL.createObjectURL(clip.blob);urls.push(url);link.href=url;link.download=clip.filename;link.textContent='Download unsaved recording now';list.prepend(link);}
  async function keep(blob,context){const ext=blob.type.includes('mpeg')?'mp3':blob.type.includes('wav')?'wav':blob.type.includes('aac')?'aac':blob.type.includes('mp4')?'m4a':blob.type.includes('ogg')?'ogg':'webm';const clip={id:crypto.randomUUID(),scope:context.scope,date:context.date,createdAt:new Date().toISOString(),label:context.label,filename:'eye-of-garden-voice-'+context.date+'.'+ext,blob};try{await saveClip(clip);if(scope===context.scope){say('Recording saved on this device. Download a copy for safekeeping.');await clips();}}catch{if(scope===context.scope){say('Recording could not be saved. Download it now before closing this page.');offerDownload(clip);}}}
  function stopRecording(){if(recorder?.state==='recording'){busy=true;recorder.stop();}stream?.getTracks().forEach(t=>t.stop());clearTimeout(recordTimer);clearInterval(clockTimer);}
  $('[data-stop-record]').onclick=stopRecording;
  $('[data-record]').onclick=async()=>{if(busy||recognizer||recorder?.state==='recording')return;if(!$('[data-consent]').checked){say('Confirm permission from the people being recorded first.');return;}if(!validDate(form.elements.date.value)){say('Choose a valid day first.');return;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){say('Recording is unavailable here. Use your phone’s recorder and add the audio file below.');return;}const context={scope,date:form.elements.date.value,label:form.elements.kind.value==='doctorAdvice'?'Doctor advice':'My voice note'};busy=true;controls();say('Waiting for microphone permission…');try{stream=await navigator.mediaDevices.getUserMedia({audio:true});if(context.scope!==scope){stream.getTracks().forEach(t=>t.stop());return;}const mime=['audio/mp4','audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus'].find(type=>MediaRecorder.isTypeSupported(type));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:{});const chunks=[];let size=0;recorder.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);size+=e.data.size;if(size>20*1024*1024)stopRecording();}};recorder.onerror=()=>{say('Recording was interrupted. Any captured audio will be saved if possible.');stopRecording();};recorder.onstop=async()=>{stream?.getTracks().forEach(t=>t.stop());clearTimeout(recordTimer);clearInterval(clockTimer);const blob=new Blob(chunks,{type:recorder.mimeType||mime||'audio/webm'});recorder=null;busy=false;controls();if(blob.size)await keep(blob,context);else say('No audio was captured. Try again when ready.');};recorder.start(1000);startTime=Date.now();clockTimer=setInterval(()=>say('Recording · '+Math.floor((Date.now()-startTime)/1000)+' seconds. Stop when finished.'),1000);recordTimer=setTimeout(stopRecording,300000);say('Recording…');}catch(error){stream?.getTracks().forEach(t=>t.stop());say(error.name==='NotAllowedError'?'Microphone permission was declined. You can type a note or add a recording file.':'Microphone unavailable. Check permission and try again.');}finally{busy=false;controls();}};
  $('[data-audio-file]').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!file.type.startsWith('audio/')||file.size>20*1024*1024||!validDate(form.elements.date.value)){say('Choose an audio file up to 20 MB and a valid day.');return;}if(!$('[data-consent]').checked){say('Confirm permission from the recorded people first.');return;}await keep(file,{scope,date:form.elements.date.value,label:'Added audio note'});e.target.value='';};
  $('[data-dictate]').onclick=()=>{const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){draftSay('Dictation is not available in this browser. Use the microphone on your phone’s keyboard, or type.');return;}if(!confirm('Your browser may send speech to its speech-recognition service to turn it into text. Continue?'))return;const base=form.elements.text.value.trim(),parts=new Map(),targetScope=scope;recognizer=new Speech();recognizer.lang=$('[data-language]').value;recognizer.continuous=true;recognizer.interimResults=true;recognizer.onresult=e=>{if(targetScope!==scope)return;for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal)parts.set(i,e.results[i][0].transcript);}form.elements.text.value=[base,...parts.values()].filter(Boolean).join(' ').slice(0,1000);saveDraft();};recognizer.onerror=e=>{draftSay(e.error==='not-allowed'?'Speech permission was declined. You can still type.':'Dictation stopped. Review the words captured, then try again if needed.');};recognizer.onend=()=>{recognizer=null;controls();saveDraft();};try{recognizer.start();draftSay('Listening… speak your note. Stop and review before saving.');controls();}catch{recognizer=null;controls();draftSay('Dictation could not start. Use your phone keyboard microphone or type.');}};
  $('[data-stop-dictate]').onclick=()=>recognizer?.stop();
  form.onsubmit=e=>{e.preventDefault();if(recognizer||recorder?.state==='recording')return;try{bridge.saveNote({date:form.elements.date.value,kind:form.elements.kind.value,text:form.elements.text.value.trim()});form.elements.text.value='';saveDraft();draftSay('Note added to your daily record.');}catch(error){draftSay(error.message);}};
  function refresh(){const next=bridge.scope(),date=bridge.day();if(next!==scope){stopRecording();recognizer?.abort();scope=next;currentDay=date;form.elements.date.value=date;form.elements.text.value='';form.elements.kind.value='noteType';try{const draft=JSON.parse(localStorage.getItem(draftKey())||'null');if(draft&&validDate(draft.date)&&typeof draft.text==='string'){form.elements.date.value=draft.date;form.elements.text.value=draft.text.slice(0,1000);form.elements.kind.value=draft.kind||'noteType';}}catch{}$('[data-consent]').checked=false;clips();}else if(date!==currentDay){currentDay=date;if(!form.elements.text.value&&!recognizer&&!recorder){form.elements.date.value=date;clips();}}controls();}
  document.addEventListener('visibilitychange',()=>{if(document.hidden){stopRecording();recognizer?.stop();}});window.addEventListener('beforeunload',e=>{if(busy||recorder?.state==='recording'||recognizer){e.preventDefault();e.returnValue='';}});refresh();return {refresh};
}
